[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.11" 