[build]
builder = "nixpacks"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.11"
DATABASE_URL = "postgresql://postgres:yAIFoMtwAPNOFVqwoJAHEmNpTDewqPWG@crossover.proxy.rlwy.net:42276/railway"
