[build]
builder = "nixpacks"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.11"
DATABASE_URL = "postgresql://signa-admin:Petare0107@signalife-signalife-xcgch6:5432/signadb"
